name: MyNicholsWorth
favicon: null
layout_spectrum: 0.50601
typography_spectrum: 0.3691756
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010b03'
    - '#7e0c01'
    - '#517b00'
    - '#bfcb00'
    - '#00be00'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
