name: MyNicholsWorth
favicon: null
layout_spectrum: 0.55105
typography_spectrum: 0.60511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e1e1e'
    - '#7c895d'
    - '#d65481'
    - '#a2c9e0'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
