favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
color:
  saturation: 0.718638
  brandStrength: 0.6612903
  rhythmicContrast: 0.3064516
  brandColors:
    - '#FFFFFF'
    - '#AB6543'
    - '#546392'
    - '#5B4C39'
    - '#90927F'
  lightness: 0
typography_spectrum: 0.281362
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
name: MyNicholsWorth
