favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
color:
  saturation: 0.7114695
  brandStrength: 0.6863799
  rhythmicContrast: 0.374552
  brandColors:
    - '#020201'
    - '#3B4249'
    - '#FFAC5C'
    - '#4B2617'
  lightness: 0.4426523
typography_spectrum: 0.6792115
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: MyNicholsWorth
