name: MyNicholsWorth
favicon: null
layout_spectrum: 0.15316
typography_spectrum: 0.40992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232c49'
    - '#97bff2'
    - '#edeee9'
    - '#847a85'
    - '#d89a85'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
