name: MyNicholsWorth
favicon: null
layout_spectrum: 0.63666
typography_spectrum: 0.62613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#ff765b'
    - '#6b5b4b'
    - '#cc3965'
    - '#ece9e4'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
    url: null
