name: MyNicholsWorth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90467
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#AB6543'
    - '#546392'
    - '#5B4C39'
    - '#90927F'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
