analytics:
  twitter: null
  google: null
  facebook: null
name: MyNicholsWorth
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
typography_spectrum: 0.81454
color:
  saturation: 0.6648746
  lightness: 0.7849463
  brandStrength: 0.4193548
  brandColors:
    - '#807665'
    - '#281E18'
    - '#C7BCA3'
    - '#C78F65'
    - '#EAFFFF'
  rhythmicContrast: 0.344086
layout_spectrum: 0.5698925
cta:
  bucket: null
  version: null
  domain: null
favicon: null
