layout_spectrum: 0.7275985
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
color:
  saturation: 0.8125
  brandStrength: 0.25
  lightness: 0.8458781
  brandColors:
    - '#100f15'
    - '#8b7965'
    - '#613311'
    - '#691312'
    - '#a8a294'
  rhythmicContrast: 0.8351254
typography_spectrum: 0.81454
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: MyNicholsWorth
