name: MyNicholsWorth
favicon: null
layout_spectrum: 0.35586
typography_spectrum: 0.9707
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#643f31'
    - '#ab7259'
    - '#dca48c'
    - '#347ba2'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
