name: MyNicholsWorth
favicon: null
layout_spectrum: 0.40241
typography_spectrum: 0.56607
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#009ef9'
    - '#9e9e9c'
    - '#fd6a5c'
    - '#daf49d'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
