analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
color:
  saturation: 0.3136201
  brandStrength: 0.2240143
  lightness: 0.6935484
  brandColors:
    - '#807665'
    - '#281E18'
    - '#C7BCA3'
    - '#C78F65'
    - '#EAFFFF'
  rhythmicContrast: 0.5734767
typography_spectrum: 0.6612903
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.09498208
favicon: null
name: MyNicholsWorth
