name: MyNicholsWorth
favicon: null
layout_spectrum: 0.3727598
typography_spectrum: 0.421147
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1e1e1e'
    - '#7c895d'
    - '#d65481'
    - '#a2c9e0'
  brandStrength: 0.2777778
  lightness: 0.3655914
  saturation: 0.874552
  rhythmicContrast: 0.6577061
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
