analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose:
  - name: awareness
    url: null
    item: 567b109d-db03-45f0-af4e-c18db8b2d7c1
color:
  saturation: 0.6810036
  brandStrength: 0.3870968
  lightness: 0.672043
  brandColors:
    - '#FFFFFF'
    - '#AB6543'
    - '#546392'
    - '#5B4C39'
    - '#90927F'
  rhythmicContrast: 0.4749104
typography_spectrum: 0.8064516
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2562724
favicon: null
name: MyNicholsWorth
