name: MyNicholsWorth
favicon: null
layout_spectrum: 0.45646
typography_spectrum: 0.18769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1916'
    - '#a1a783'
    - '#737f57'
    - '#4d4924'
    - '#4e6551'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: null
    url: null
